/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MuseumRouteImport } from './routes/museum'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MuseumIndexRouteImport } from './routes/museum.index'
import { Route as MuseumSlugRouteImport } from './routes/museum.$slug'

const MuseumRoute = MuseumRouteImport.update({
  id: '/museum',
  path: '/museum',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MuseumIndexRoute = MuseumIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MuseumRoute,
} as any)
const MuseumSlugRoute = MuseumSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MuseumRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/museum': typeof MuseumRouteWithChildren
  '/museum/$slug': typeof MuseumSlugRoute
  '/museum/': typeof MuseumIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/museum/$slug': typeof MuseumSlugRoute
  '/museum': typeof MuseumIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/museum': typeof MuseumRouteWithChildren
  '/museum/$slug': typeof MuseumSlugRoute
  '/museum/': typeof MuseumIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/museum' | '/museum/$slug' | '/museum/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/museum/$slug' | '/museum'
  id: '__root__' | '/' | '/contact' | '/museum' | '/museum/$slug' | '/museum/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  MuseumRoute: typeof MuseumRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/museum': {
      id: '/museum'
      path: '/museum'
      fullPath: '/museum'
      preLoaderRoute: typeof MuseumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/museum/': {
      id: '/museum/'
      path: '/'
      fullPath: '/museum/'
      preLoaderRoute: typeof MuseumIndexRouteImport
      parentRoute: typeof MuseumRoute
    }
    '/museum/$slug': {
      id: '/museum/$slug'
      path: '/$slug'
      fullPath: '/museum/$slug'
      preLoaderRoute: typeof MuseumSlugRouteImport
      parentRoute: typeof MuseumRoute
    }
  }
}

interface MuseumRouteChildren {
  MuseumSlugRoute: typeof MuseumSlugRoute
  MuseumIndexRoute: typeof MuseumIndexRoute
}

const MuseumRouteChildren: MuseumRouteChildren = {
  MuseumSlugRoute: MuseumSlugRoute,
  MuseumIndexRoute: MuseumIndexRoute,
}

const MuseumRouteWithChildren =
  MuseumRoute._addFileChildren(MuseumRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  MuseumRoute: MuseumRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
